theme: jekyll-theme-slate
title: Aaron Bauman
description: Senior Software Engineer at [Message Agency](https://www.messageagency.com)
avatar: https://avatars2.githubusercontent.com/u/508451
url: https://www.messageagency.com
